"""
Reemplaza la celda placeholder del VAR (cell 26) en 02b con la implementación
completa: lags dinámicos, estimación de todos los modelos, FEVD y gráficos.
"""
import json, copy, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

NB_PATH = 'notebooks/02b_analisis_completo.ipynb'

with open(NB_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Encontrar la celda 26 (placeholder VAR) - buscar por contenido
var_cell_idx = None
for i, c in enumerate(nb['cells']):
    src = ''.join(c.get('source', []))
    if '8.1-8.6  Verificación VAR' in src or '8.1-8.6  Verificaci' in src:
        var_cell_idx = i
        break

if var_cell_idx is None:
    raise RuntimeError("No se encontró la celda placeholder del VAR")

print(f"Celda placeholder encontrada en index {var_cell_idx}")

# Construir las nuevas celdas
new_cells = []

# ── CELDA 8.1: Lags dinámicos + estimación VAR ──
new_cells.append({
    'cell_type': 'code',
    'metadata': {},
    'outputs': [],
    'execution_count': None,
    'source': [
"# ═══════════════════════════════════════════════════════════════════════════\n",
"# 8.1  ESTIMACIÓN VAR — TODAS LAS COMBINACIONES\n",
"#      Lags máximos dinámicos por combinación + orden Cholesky por ranking\n",
"# ═══════════════════════════════════════════════════════════════════════════\n",
"from statsmodels.tsa.api import VAR as _VAR_est\n",
"from statsmodels.stats.diagnostic import acorr_ljungbox as _lb_var\n",
"from itertools import combinations as _comb_var\n",
"\n",
"print('═'*70)\n",
"print('8.1  ESTIMACIÓN VAR — TODAS LAS COMBINACIONES')\n",
"print('═'*70)\n",
"\n",
"# ── Orden jerárquico de Cholesky (del ranking de exogeneidad) ──────────\n",
"if ranking_exogeneidad.empty:\n",
"    raise RuntimeError('ranking_exogeneidad vacío. Ejecutar sección 7.3.')\n",
"\n",
"CHOLESKY_ORDER = list(ranking_exogeneidad.index)  # más exógena primero\n",
"print(f'Orden Cholesky (exógena → endógena):')\n",
"for _i_ch, _v_ch in enumerate(CHOLESKY_ORDER, 1):\n",
"    print(f'  [{_i_ch}] {COL_LABEL.get(_v_ch, _v_ch)}')\n",
"\n",
"# ── Generar combinaciones ──────────────────────────────────────────────\n",
"_vars_est = [v for v in CHOLESKY_ORDER if v in X_SAFE_EST or v == Y_SAFE]\n",
"_combos_var = []\n",
"# VAR necesita al menos 2 variables; siempre incluimos Y_SAFE\n",
"_others = [v for v in _vars_est if v != Y_SAFE]\n",
"_max_k = len(_others) if MAX_VARS_POR_MODELO is None else min(MAX_VARS_POR_MODELO, len(_others))\n",
"for _k in range(1, _max_k + 1):\n",
"    for _c in _comb_var(_others, _k):\n",
"        _combos_var.append(list(_c))\n",
"\n",
"if MAX_COMBINACIONES is not None and len(_combos_var) > MAX_COMBINACIONES:\n",
"    random.seed(SEMILLA)\n",
"    _combos_var = random.sample(_combos_var, MAX_COMBINACIONES)\n",
"\n",
"print(f'\\nCombinaciones a estimar: {len(_combos_var)}')\n",
"print(f'Variables disponibles:  {len(_vars_est)}')\n",
"\n",
"# ── Loop de estimación ─────────────────────────────────────────────────\n",
"var_results = []\n",
"_n_ok = _n_fail = 0\n",
"\n",
"for _ci, _x_combo in enumerate(_combos_var):\n",
"    try:\n",
"        # Variables del modelo: Y + combo, ordenadas según Cholesky\n",
"        _all_v = [Y_SAFE] + list(_x_combo)\n",
"        _ordered = [v for v in CHOLESKY_ORDER if v in _all_v]\n",
"\n",
"        _df_var = df_safe[_ordered].dropna()\n",
"        _T = len(_df_var)\n",
"        _K = len(_ordered)\n",
"\n",
"        if _T < 30:\n",
"            continue\n",
"\n",
"        # ── Lags máximos dinámicos: floor((T-1) / (K+1)), mínimo 1, máximo MAX_LAGS_VAR\n",
"        _max_p = min(MAX_LAGS_VAR, max(1, int((_T - 1) / (_K + 1))))\n",
"\n",
"        # ── Selección de orden por BIC ─────────────────────────────────\n",
"        _model = _VAR_est(_df_var)\n",
"        try:\n",
"            _sel = _model.select_order(maxlags=_max_p)\n",
"            _p_bic = max(1, _sel.selected_orders.get('bic', 1))\n",
"        except Exception:\n",
"            _p_bic = 1\n",
"\n",
"        # ── Estimar VAR ───────────────────────────────────────────────\n",
"        _fit = _model.fit(_p_bic)\n",
"\n",
"        # ── Diagnóstico: Ljung-Box sobre residuos de la ecuación Y ───\n",
"        _y_idx = list(_ordered).index(Y_SAFE)\n",
"        _resid_y = _fit.resid[:, _y_idx]\n",
"        _lb_lags = min(10, len(_resid_y) // 5)\n",
"        try:\n",
"            _lb_res = _lb_var(_resid_y, lags=_lb_lags, return_df=True)\n",
"            _lb_p = float(_lb_res['lb_pvalue'].iloc[-1])\n",
"        except Exception:\n",
"            _lb_p = np.nan\n",
"\n",
"        _is_white = (not np.isnan(_lb_p)) and (_lb_p >= 0.05)\n",
"\n",
"        # ── Estabilidad (raíces < 1) ──────────────────────────────────\n",
"        _stable = _fit.is_stable(verbose=False)\n",
"\n",
"        # ── Métricas ──────────────────────────────────────────────────\n",
"        # R² de la ecuación Y\n",
"        _ss_res = np.sum(_resid_y**2)\n",
"        _y_vals = _df_var[Y_SAFE].values[_p_bic:]\n",
"        _ss_tot = np.sum((_y_vals - np.mean(_y_vals))**2)\n",
"        _r2 = 1 - _ss_res / _ss_tot if _ss_tot > 0 else 0\n",
"        _n_params = _K * _p_bic + 1\n",
"        _r2_adj = 1 - (1 - _r2) * (len(_y_vals) - 1) / max(1, len(_y_vals) - _n_params - 1)\n",
"\n",
"        var_results.append({\n",
"            'x_vars': tuple(_x_combo),\n",
"            'ordered_vars': tuple(_ordered),\n",
"            'n_vars': _K,\n",
"            'T': _T,\n",
"            'max_p_allowed': _max_p,\n",
"            'p_selected': _p_bic,\n",
"            'R2_adj': _r2_adj,\n",
"            'AIC': _fit.aic,\n",
"            'BIC': _fit.bic,\n",
"            'HQ': _fit.hqic,\n",
"            'LB_pvalue': _lb_p,\n",
"            'stable': _stable,\n",
"            'resid_ruido_blanco': _is_white,\n",
"        })\n",
"        _n_ok += 1\n",
"\n",
"    except Exception as _e:\n",
"        _n_fail += 1\n",
"        continue\n",
"\n",
"    if (_ci + 1) % 50 == 0:\n",
"        print(f'  {_ci+1}/{len(_combos_var)} ...  OK={_n_ok}  fail={_n_fail}')\n",
"\n",
"df_var_full = pd.DataFrame(var_results)\n",
"print(f'\\n✅ Modelos VAR estimados: {len(df_var_full)}')\n",
"if not df_var_full.empty:\n",
"    _n_w = df_var_full['resid_ruido_blanco'].sum()\n",
"    _n_s = df_var_full['stable'].sum()\n",
"    print(f'   Ruido blanco: {_n_w} ({_n_w/len(df_var_full)*100:.1f}%)')\n",
"    print(f'   Estables:     {_n_s} ({_n_s/len(df_var_full)*100:.1f}%)')\n",
"    print(f'   BIC medio:    {df_var_full[\"BIC\"].mean():.2f}')\n",
"    print(f'   R² adj medio: {df_var_full[\"R2_adj\"].mean():.4f}')\n",
]
})

# ── CELDA 8.2: Markdown FEVD ──
new_cells.append({
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
"### 8.2 FEVD — Descomposición de Varianza del Error de Pronóstico\n",
"\n",
"> Para cada modelo con residuos de ruido blanco y BIC < media,\n",
"> calcular la FEVD y registrar qué variables explican más varianza del EMBI.\n",
"> Se muestran los top 5 modelos según BIC."
    ]
})

# ── CELDA 8.2: FEVD + gráficos ──
new_cells.append({
    'cell_type': 'code',
    'metadata': {},
    'outputs': [],
    'execution_count': None,
    'source': [
"# ═══════════════════════════════════════════════════════════════════════════\n",
"# 8.2  FEVD — TOP 5 MODELOS (ruido blanco + BIC < media)\n",
"# ═══════════════════════════════════════════════════════════════════════════\n",
"\n",
"print('═'*70)\n",
"print('8.2  FEVD — DESCOMPOSICIÓN DE VARIANZA DEL ERROR DE PRONÓSTICO')\n",
"print('═'*70)\n",
"\n",
"if df_var_full.empty:\n",
"    print('⚠️  Sin modelos VAR. Ejecutar sección 8.1.')\n",
"else:\n",
"    # ── Filtrar: ruido blanco + estable + BIC < media ──────────────────\n",
"    _df_ok = df_var_full[\n",
"        (df_var_full['resid_ruido_blanco'] == True) &\n",
"        (df_var_full['stable'] == True)\n",
"    ].copy()\n",
"\n",
"    if _df_ok.empty:\n",
"        print('⚠️  Ningún modelo pasa ruido blanco + estabilidad.')\n",
"        print('    Usando todos los modelos estables como fallback.')\n",
"        _df_ok = df_var_full[df_var_full['stable'] == True].copy()\n",
"\n",
"    if not _df_ok.empty:\n",
"        _bic_mean = _df_ok['BIC'].mean()\n",
"        _df_good = _df_ok[_df_ok['BIC'] < _bic_mean].copy()\n",
"        if _df_good.empty:\n",
"            _df_good = _df_ok.copy()\n",
"        _df_good = _df_good.sort_values('BIC').head(5).reset_index(drop=True)\n",
"\n",
"        print(f'Modelos con ruido blanco + estables: {len(_df_ok)}')\n",
"        print(f'BIC medio: {_bic_mean:.2f}')\n",
"        print(f'Top 5 por BIC (de {len(_df_ok)} filtrados):\\n')\n",
"\n",
"        # ── Horizonte FEVD ─────────────────────────────────────────────\n",
"        FEVD_HORIZONTE = 24  # períodos hacia adelante\n",
"\n",
"        _COLORS_FEVD = plt.cm.tab10.colors\n",
"\n",
"        for _rank, _row in _df_good.iterrows():\n",
"            _ordered = list(_row['ordered_vars'])\n",
"            _p = int(_row['p_selected'])\n",
"            _df_v = df_safe[_ordered].dropna()\n",
"\n",
"            try:\n",
"                _fit = _VAR_est(_df_v).fit(_p)\n",
"                _fevd = _fit.fevd(FEVD_HORIZONTE)\n",
"            except Exception as _e:\n",
"                print(f'  Error FEVD modelo {_rank+1}: {_e}')\n",
"                continue\n",
"\n",
"            # Índice de Y en el modelo\n",
"            _y_idx = _ordered.index(Y_SAFE)\n",
"            _decomp = _fevd.decomp  # shape (horizonte, K, K)\n",
"            # FEVD de Y: _decomp[:, _y_idx, :] → (horizonte, K)\n",
"            _fevd_y = _decomp[:, _y_idx, :]  # cada columna = contribución de var j a Y\n",
"\n",
"            _labels_v = [COL_LABEL.get(v, v)[:25] for v in _ordered]\n",
"            _vars_str = ', '.join([COL_LABEL.get(v, v)[:20] for v in _row['x_vars']])\n",
"\n",
"            print(f'\\n── Modelo {_rank+1}: BIC={_row[\"BIC\"]:.1f}  '\n",
"                  f'p={_p}  R²adj={_row[\"R2_adj\"]:.3f}  '\n",
"                  f'LB_p={_row[\"LB_pvalue\"]:.3f}')\n",
"            print(f'   Vars: {_vars_str}')\n",
"            print(f'   Orden: {\" → \".join(_labels_v)}')\n",
"\n",
"            # ── Tabla FEVD a horizontes seleccionados ──────────────────\n",
"            _horizons = [1, 3, 6, 12, min(FEVD_HORIZONTE, 24)]\n",
"            _horizons = sorted(set(h for h in _horizons if h <= FEVD_HORIZONTE))\n",
"            _fevd_table = pd.DataFrame(\n",
"                {f'h={h}': _fevd_y[h-1] for h in _horizons},\n",
"                index=_labels_v\n",
"            ).T\n",
"            print(_fevd_table.round(4).to_string())\n",
"\n",
"            # ── Gráfico de barras apiladas ─────────────────────────────\n",
"            fig, ax = plt.subplots(figsize=(12, 5))\n",
"            _x_pos = np.arange(FEVD_HORIZONTE)\n",
"            _bottom = np.zeros(FEVD_HORIZONTE)\n",
"\n",
"            for _j, _lbl in enumerate(_labels_v):\n",
"                _vals = _fevd_y[:, _j]\n",
"                ax.bar(_x_pos, _vals, bottom=_bottom,\n",
"                       label=_lbl, color=_COLORS_FEVD[_j % len(_COLORS_FEVD)],\n",
"                       edgecolor='white', linewidth=0.3)\n",
"                _bottom += _vals\n",
"\n",
"            ax.set_xlabel('Horizonte (períodos)', fontsize=10)\n",
"            ax.set_ylabel('Proporción de varianza explicada', fontsize=10)\n",
"            ax.set_title(\n",
"                f'FEVD del {COL_LABEL.get(Y_SAFE, Y_SAFE)[:30]} — '\n",
"                f'Modelo {_rank+1} (BIC={_row[\"BIC\"]:.0f}, p={_p})',\n",
"                fontsize=11\n",
"            )\n",
"            ax.set_xticks(_x_pos[::2])\n",
"            ax.set_xticklabels([str(h+1) for h in _x_pos[::2]])\n",
"            ax.set_ylim(0, 1.05)\n",
"            ax.legend(loc='center left', bbox_to_anchor=(1, 0.5), fontsize=8)\n",
"            plt.tight_layout()\n",
"            plt.show()\n",
"\n",
"        # ── Resumen comparativo FEVD h=12 de los 5 modelos ────────────\n",
"        print('\\n' + '═'*70)\n",
"        print('  RESUMEN FEVD h=12 — TOP 5 MODELOS')\n",
"        print('═'*70)\n",
"    else:\n",
"        print('⚠️  Ningún modelo VAR es estable.')\n",
]
})

# ── Reemplazar la celda placeholder y el markdown anterior ──
# El markdown de la sección 8 (cell 25) se mantiene, solo reemplazamos cell 26
nb['cells'] = nb['cells'][:var_cell_idx] + new_cells + nb['cells'][var_cell_idx+1:]

with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"✅ Notebook actualizado: {len(new_cells)} celdas reemplazan la celda {var_cell_idx}")
print(f"   Total celdas ahora: {len(nb['cells'])}")
