"""
glosario.py - Catálogo de series de tiempo disponibles
Trabajo Final de Grado - Riesgo País Argentino
"""

import os
import pandas as pd
from typing import Optional

# Ruta base del proyecto (relativa a cualquier script que importe este módulo)
_BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))


GLOSARIO = [
    # ===================================================================
    # VARIABLE DEPENDIENTE
    # ===================================================================
    {
        'id': 'embi_arg',
        'nombre': 'EMBI+ Argentina',
        'fuente': 'global',
        'categoria': 'dependiente',
        'archivo': 'data/raw/global/riesgo_pais_arg.csv',
        'col_fecha': 'fecha',
        'col_valor': 'embi_arg',
        'descripcion': 'Riesgo país argentino medido por el EMBI+ de J.P. Morgan',
        'frecuencia': 'diaria',
        'unidad': 'puntos básicos',
        'desde': '1999-01-22',
        'hasta': '2026-04-24',
    },

    # ===================================================================
    # GLOBAL - Mercados financieros internacionales
    # ===================================================================
    {
        'id': 'vix',
        'nombre': 'VIX',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/vix.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Índice de volatilidad implícita del S&P 500 (CBOE)',
        'frecuencia': 'diaria',
        'unidad': 'puntos',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'move',
        'nombre': 'MOVE Index',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/move.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'ICE BofA MOVE Index — volatilidad implícita del mercado de bonos del Tesoro EEUU',
        'frecuencia': 'diaria',
        'unidad': 'puntos básicos',
        'desde': '2002-11-12',
        'hasta': '2026-04-22',
    },
    {
        'id': 'dxy',
        'nombre': 'DXY (Índice del Dólar)',
        'fuente': 'global',
        'categoria': 'cambiario',
        'archivo': 'data/raw/global/dxy.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Índice del dólar estadounidense contra una canasta de monedas principales',
        'frecuencia': 'diaria',
        'unidad': 'índice',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'sp500',
        'nombre': 'S&P 500',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/sp500.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Índice bursátil S&P 500',
        'frecuencia': 'diaria',
        'unidad': 'puntos',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'msci_em',
        'nombre': 'MSCI Emergentes',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/msci_em.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Índice MSCI de mercados emergentes',
        'frecuencia': 'diaria',
        'unidad': 'puntos',
        'desde': '2003-04-14',
        'hasta': '2026-04-22',
    },
    {
        'id': 'embi_latam',
        'nombre': 'EMBI Latinoamérica',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/embi_latam.csv',
        'col_fecha': 'fecha',
        'col_valor': 'embi_latam',
        'descripcion': 'Spread EMBI promedio de países latinoamericanos',
        'frecuencia': 'diaria',
        'unidad': 'puntos básicos',
        'desde': '2007-10-29',
        'hasta': '2026-04-22',
    },
    {
        'id': 'ofr_fsi',
        'nombre': 'OFR Financial Stress Index',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/ofr_fsi.csv',
        'col_fecha': 'Date',
        'col_valor': 'OFR FSI',
        'descripcion': 'Índice de estrés financiero de la Oficina de Investigación Financiera de EEUU',
        'frecuencia': 'diaria',
        'unidad': 'índice estandarizado',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    # Bonos del Tesoro EEUU
    {
        'id': 'ust2y',
        'nombre': 'UST 2Y',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/ust2y.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Rendimiento del bono del Tesoro de EEUU a 2 años',
        'frecuencia': 'diaria',
        'unidad': '% anual',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'ust5y',
        'nombre': 'UST 5Y',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/ust5y.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Rendimiento del bono del Tesoro de EEUU a 5 años',
        'frecuencia': 'diaria',
        'unidad': '% anual',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'ust10y',
        'nombre': 'UST 10Y',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/ust10y.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Rendimiento del bono del Tesoro de EEUU a 10 años',
        'frecuencia': 'diaria',
        'unidad': '% anual',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'ust30y',
        'nombre': 'UST 30Y',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/ust30y.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Rendimiento del bono del Tesoro de EEUU a 30 años',
        'frecuencia': 'diaria',
        'unidad': '% anual',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    # Monedas LATAM
    {
        'id': 'brl',
        'nombre': 'BRL/USD',
        'fuente': 'global',
        'categoria': 'cambiario',
        'archivo': 'data/raw/global/brl.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Tipo de cambio Real brasileño / Dólar',
        'frecuencia': 'diaria',
        'unidad': 'BRL por USD',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'clp',
        'nombre': 'CLP/USD',
        'fuente': 'global',
        'categoria': 'cambiario',
        'archivo': 'data/raw/global/clp.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Tipo de cambio Peso chileno / Dólar',
        'frecuencia': 'diaria',
        'unidad': 'CLP por USD',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'mxn',
        'nombre': 'MXN/USD',
        'fuente': 'global',
        'categoria': 'cambiario',
        'archivo': 'data/raw/global/mxn.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Tipo de cambio Peso mexicano / Dólar',
        'frecuencia': 'diaria',
        'unidad': 'MXN por USD',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    # Commodities
    {
        'id': 'wti',
        'nombre': 'Petróleo WTI',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/wti.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio del petróleo crudo WTI (West Texas Intermediate)',
        'frecuencia': 'diaria',
        'unidad': 'USD por barril',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'brent',
        'nombre': 'Petróleo Brent',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/brent.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio del petróleo crudo Brent',
        'frecuencia': 'diaria',
        'unidad': 'USD por barril',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'soja',
        'nombre': 'Soja',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/soja.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio de la soja en mercados internacionales (CBOT)',
        'frecuencia': 'diaria',
        'unidad': 'USD por bushel',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'maiz',
        'nombre': 'Maíz',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/maiz.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio del maíz en mercados internacionales (CBOT)',
        'frecuencia': 'diaria',
        'unidad': 'USD por bushel',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'trigo',
        'nombre': 'Trigo',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/trigo.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio del trigo en mercados internacionales (CBOT)',
        'frecuencia': 'diaria',
        'unidad': 'USD por bushel',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'oro',
        'nombre': 'Oro',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/oro.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio del oro en mercados internacionales',
        'frecuencia': 'diaria',
        'unidad': 'USD por onza troy',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'cobre',
        'nombre': 'Cobre',
        'fuente': 'global',
        'categoria': 'commodity',
        'archivo': 'data/raw/global/cobre.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Precio del cobre en mercados internacionales',
        'frecuencia': 'diaria',
        'unidad': 'USD por libra',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },

    # ===================================================================
    # FRED - Federal Reserve Economic Data
    # ===================================================================
    {
        'id': 'fred_embi_global',
        'nombre': 'EMBI Global (FRED)',
        'fuente': 'fred',
        'categoria': 'mercado',
        'archivo': 'raw/global/fred_embi_global.csv',
        'col_fecha': 'fecha',
        'col_valor': 'embi_global_oas',
        'descripcion': 'EMBI Global Spread (OAS) de J.P. Morgan vía FRED',
        'frecuencia': 'diaria',
        'unidad': 'puntos básicos',
        'desde': '2023-04-24',
        'hasta': '2026-04-24',
    },
    {
        'id': 'fred_fedfunds',
        'nombre': 'Fed Funds Rate',
        'fuente': 'fred',
        'categoria': 'mercado',
        'archivo': 'raw/global/fred_fedfunds.csv',
        'col_fecha': 'fecha',
        'col_valor': 'fed_funds_rate',
        'descripcion': 'Tasa de política monetaria de la Reserva Federal de EEUU',
        'frecuencia': 'diaria',
        'unidad': '% anual',
        'desde': '2000-01-01',
        'hasta': '2026-04-24',
    },
    {
        'id': 'fred_t10y2y',
        'nombre': 'Spread 10Y-2Y (curva EEUU)',
        'fuente': 'fred',
        'categoria': 'mercado',
        'archivo': 'raw/global/fred_t10y2y.csv',
        'col_fecha': 'fecha',
        'col_valor': 'ust_spread_10y2y',
        'descripcion': 'Pendiente de la curva de rendimientos de EEUU (diferencia 10Y - 2Y)',
        'frecuencia': 'diaria',
        'unidad': 'puntos porcentuales',
        'desde': '2000-01-03',
        'hasta': '2026-04-24',
    },
    {
        'id': 'fred_us_hy_oas',
        'nombre': 'US High Yield OAS',
        'fuente': 'fred',
        'categoria': 'mercado',
        'archivo': 'raw/global/fred_us_hy_oas.csv',
        'col_fecha': 'fecha',
        'col_valor': 'us_hy_oas',
        'descripcion': 'Spread de bonos corporativos High Yield de EEUU (Option-Adjusted Spread)',
        'frecuencia': 'diaria',
        'unidad': 'puntos básicos',
        'desde': '2023-04-24',
        'hasta': '2026-04-24',
    },
    {
        'id': 'fred_vix',
        'nombre': 'VIX (FRED)',
        'fuente': 'fred',
        'categoria': 'mercado',
        'archivo': 'raw/global/fred_vix.csv',
        'col_fecha': 'fecha',
        'col_valor': 'vix_fred',
        'descripcion': 'VIX histórico desde FRED (CBOE Volatility Index)',
        'frecuencia': 'diaria',
        'unidad': 'puntos',
        'desde': '2000-01-03',
        'hasta': '2026-04-24',
    },

    # ===================================================================
    # BCRA - Banco Central de la República Argentina
    # ===================================================================
    {
        'id': 'reservas_brutas',
        'nombre': 'Reservas Internacionales BCRA',
        'fuente': 'bcra',
        'categoria': 'externo',
        'archivo': 'data/raw/bcra/001_reservas_brutas.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Reservas internacionales brutas del BCRA',
        'frecuencia': 'diaria',
        'unidad': 'millones USD',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'tc_minorista',
        'nombre': 'TC Minorista (BNA)',
        'fuente': 'bcra',
        'categoria': 'cambiario',
        'archivo': 'data/raw/bcra/004_tc_minorista.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Tipo de cambio minorista (promedio vendedor) - Banco Nación Argentina',
        'frecuencia': 'diaria',
        'unidad': 'ARS por USD',
        'desde': '2010-06-01',
        'hasta': '2026-04-22',
    },
    {
        'id': 'tc_mayorista',
        'nombre': 'TC Mayorista A3500',
        'fuente': 'bcra',
        'categoria': 'cambiario',
        'archivo': 'data/raw/bcra/005_tc_mayorista_a3500.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Tipo de cambio mayorista de referencia BCRA (comunicación A3500)',
        'frecuencia': 'diaria',
        'unidad': 'ARS por USD',
        'desde': '2003-01-02',
        'hasta': '2026-04-22',
    },
    {
        'id': 'tasa_badlar',
        'nombre': 'Tasa BADLAR (privados)',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/007_tasa_badlar_privados.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Tasa BADLAR de bancos privados (depósitos > $1M, 30-35 días)',
        'frecuencia': 'diaria',
        'unidad': '% TNA',
        'desde': '2003-01-02',
        'hasta': '2026-04-21',
    },
    {
        'id': 'tasa_tm20',
        'nombre': 'Tasa TM20 (privados)',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/008_tasa_tm20_privados.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Tasa TM20 de bancos privados (depósitos > $20M, 30-35 días)',
        'frecuencia': 'diaria',
        'unidad': '% TNA',
        'desde': '2017-01-02',
        'hasta': '2026-04-21',
    },
    {
        'id': 'tasa_dep_30d',
        'nombre': 'Tasa Depósitos 30 días',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/012_tasa_dep_30d.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Tasa de interés de depósitos a plazo fijo de 30 días',
        'frecuencia': 'diaria',
        'unidad': '% TNA',
        'desde': '2003-01-02',
        'hasta': '2026-04-21',
    },
    {
        'id': 'base_monetaria',
        'nombre': 'Base Monetaria',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/015_base_monetaria.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Base monetaria (circulante + reservas bancarias en BCRA)',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'dep_total',
        'nombre': 'Depósitos Totales',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/021_dep_total.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Total de depósitos en efectivo en entidades financieras',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'dep_plazo',
        'nombre': 'Depósitos a Plazo',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/024_dep_plazo.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Depósitos a plazo fijo en el sistema financiero',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'm2',
        'nombre': 'M2',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/109_m2.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Agregado monetario M2',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-17',
    },
    {
        'id': 'prestamos_privado',
        'nombre': 'Préstamos al Sector Privado',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/026_prestamos_privado.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Préstamos del sistema financiero al sector privado',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'cer',
        'nombre': 'CER (Coeficiente de Estabilización de Referencia)',
        'fuente': 'bcra',
        'categoria': 'real',
        'archivo': 'data/raw/bcra/cer.csv',
        'col_fecha': 'fecha',
        'col_valor': 'cer',
        'descripcion': 'Coeficiente de Estabilización de Referencia — índice diario de inflación argentina (base feb-2002)',
        'frecuencia': 'diaria',
        'unidad': 'índice',
        'desde': '2003-01-02',
        'hasta': '2026-04-27',
    },
    {
        'id': 'tip_etf',
        'nombre': 'TIP ETF (TIPS Bond EEUU)',
        'fuente': 'global',
        'categoria': 'mercado',
        'archivo': 'data/raw/global/tip_etf.csv',
        'col_fecha': 'fecha',
        'col_valor': 'tip_close',
        'descripcion': 'iShares TIPS Bond ETF — proxy diario de inflación esperada en EEUU (Treasury Inflation-Protected Securities)',
        'frecuencia': 'diaria',
        'unidad': 'USD',
        'desde': '2003-12-05',
        'hasta': '2026-04-25',
    },
    {
        'id': 'pases_pasivos',
        'nombre': 'Pases Pasivos BCRA',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/152_pases_pasivos.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Stock de pases pasivos del BCRA (instrumento de absorción monetaria)',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2004-05-28',
        'hasta': '2026-04-21',
    },
    {
        'id': 'pases_activos',
        'nombre': 'Pases Activos BCRA',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/154_pases_activos.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Stock de pases activos del BCRA',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2004-05-28',
        'hasta': '2026-04-21',
    },
    {
        'id': 'leliq_notalq',
        'nombre': 'LELIQ y NOTALQ',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/155_leliq_notalq.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Stock de Letras y Notas de Liquidez del BCRA',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2018-01-11',
        'hasta': '2026-04-21',
    },
    {
        'id': 'dep_cc_privado',
        'nombre': 'Depósitos CC Sector Privado',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/022_dep_cc_privado.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Depósitos en cuenta corriente del sector privado',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'dep_cajas_ahorro',
        'nombre': 'Depósitos Cajas de Ahorro',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/023_dep_cajas_ahorro.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Depósitos en cajas de ahorro del sistema financiero',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'm2_var_anual',
        'nombre': 'M2 Variación Anual',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/025_m2_var_anual.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Variación anual del agregado monetario M2',
        'frecuencia': 'diaria',
        'unidad': '% anual',
        'desde': '2003-01-02',
        'hasta': '2026-04-17',
    },
    {
        'id': 'prest_total_privado',
        'nombre': 'Préstamos Totales al Privado',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/117_prest_total_privado.csv',
        'col_fecha': 'fecha',
        'col_valor': 'valor',
        'descripcion': 'Total de préstamos del sistema financiero al sector privado',
        'frecuencia': 'diaria',
        'unidad': 'millones ARS',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'itcrm',
        'nombre': 'ITCRM (TC Real Multilateral)',
        'fuente': 'bcra',
        'categoria': 'cambiario',
        'archivo': 'data/raw/bcra/itcrm_diario.csv',
        'col_fecha': 'Periodo',
        'col_valor': 'ITCRM ',
        'descripcion': 'Índice de Tipo de Cambio Real Multilateral del BCRA',
        'frecuencia': 'diaria',
        'unidad': 'índice (base 2010=100)',
        'desde': '1997-01-01',
        'hasta': '2026-04-22',
    },
    {
        'id': 'depositos_usd',
        'nombre': 'Depósitos en USD (totales)',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/depositos_usd_totales.csv',
        'col_fecha': 'fecha',
        'col_valor': 'depositos_usd_z',
        'descripcion': 'Depósitos totales en dólares del sistema financiero argentino',
        'frecuencia': 'mensual',
        'unidad': 'millones USD',
        'desde': '2002-12-31',
        'hasta': '2026-04-20',
    },
    {
        'id': 'depositos_usd_privado',
        'nombre': 'Depósitos en USD (sector privado no financiero)',
        'fuente': 'bcra',
        'categoria': 'monetario',
        'archivo': 'data/raw/bcra/depositos_usd_secprivnofin.csv',
        'col_fecha': 'fecha',
        'col_valor': 'depositos_usd_z',
        'descripcion': 'Depósitos en dólares del sector privado no financiero',
        'frecuencia': 'mensual',
        'unidad': 'millones USD',
        'desde': '2002-12-31',
        'hasta': '2026-04-20',
    },

    # ===================================================================
    # MEP / Blue / CCL - Tipos de cambio alternativos
    # ===================================================================
    # ⚠️ NOTA: Los archivos CSV de MEP/Blue/CCL no están descargados aún.
    # La carpeta data/raw/mep/ está vacía. Estas series están en el glosario
    # para documentación, pero no se pueden cargar hasta descargar los datos.
    {
        'id': 'tc_blue',
        'nombre': 'Dólar Blue',
        'fuente': 'mep',
        'categoria': 'cambiario',
        'archivo': 'data/raw/mep/tc_blue.csv',
        'col_fecha': 'fecha',
        'col_valor': 'venta',
        'descripcion': 'Tipo de cambio informal (dólar blue) — PENDIENTE DE DESCARGA',
        'frecuencia': 'diaria',
        'unidad': 'ARS por USD',
        'desde': '2011-01-03',
        'hasta': None,
        'disponible': False,
    },
    {
        'id': 'tc_mep',
        'nombre': 'Dólar MEP',
        'fuente': 'mep',
        'categoria': 'cambiario',
        'archivo': 'data/raw/mep/tc_mep.csv',
        'col_fecha': 'fecha',
        'col_valor': 'venta',
        'descripcion': 'Dólar MEP (bolsa) — PENDIENTE DE DESCARGA',
        'frecuencia': 'diaria',
        'unidad': 'ARS por USD',
        'desde': '2011-01-03',
        'hasta': None,
        'disponible': False,
    },
    {
        'id': 'tc_ccl',
        'nombre': 'Dólar CCL',
        'fuente': 'mep',
        'categoria': 'cambiario',
        'archivo': 'data/raw/mep/tc_ccl.csv',
        'col_fecha': 'fecha',
        'col_valor': 'venta',
        'descripcion': 'Dólar CCL (contado con liquidación) — PENDIENTE DE DESCARGA',
        'frecuencia': 'diaria',
        'unidad': 'ARS por USD',
        'desde': '2011-01-03',
        'hasta': None,
        'disponible': False,
    },

    # ===================================================================
    # LOCAL - Mercado de capitales argentino
    # ===================================================================
    {
        'id': 'merval',
        'nombre': 'MERVAL',
        'fuente': 'local',
        'categoria': 'mercado',
        'archivo': 'data/raw/local/merval.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Índice Merval — principales acciones de la Bolsa de Buenos Aires',
        'frecuencia': 'diaria',
        'unidad': 'puntos (ARS)',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'merval_usd',
        'nombre': 'MERVAL (en USD)',
        'fuente': 'local',
        'categoria': 'mercado',
        'archivo': 'data/raw/local/merval_usd.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'Índice Merval expresado en dólares estadounidenses',
        'frecuencia': 'diaria',
        'unidad': 'puntos (USD)',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'gga_adr',
        'nombre': 'Grupo Galicia ADR',
        'fuente': 'local',
        'categoria': 'mercado',
        'archivo': 'data/raw/local/gga_adr.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'ADR de Grupo Financiero Galicia en NASDAQ',
        'frecuencia': 'diaria',
        'unidad': 'USD',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },
    {
        'id': 'ypf_adr',
        'nombre': 'YPF ADR',
        'fuente': 'local',
        'categoria': 'mercado',
        'archivo': 'data/raw/local/ypf_adr.csv',
        'col_fecha': 'fecha',
        'col_valor': 'Close',
        'descripcion': 'ADR de YPF S.A. en la Bolsa de Nueva York (NYSE)',
        'frecuencia': 'diaria',
        'unidad': 'USD',
        'desde': '2000-01-03',
        'hasta': '2026-04-22',
    },

    # ===================================================================
    # INDEC - Instituto Nacional de Estadística y Censos
    # ===================================================================
    {
        'id': 'ipc_nivel',
        'nombre': 'IPC Nacional (nivel)',
        'fuente': 'indec',
        'categoria': 'real',
        'archivo': 'data/raw/indec/ipc_nacional_ndice_de_precios_al_consumidor_nivel_general_base_diciembre_.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'ipc_ng_nacional',
        'descripcion': 'Índice de Precios al Consumidor Nacional, nivel general (base dic-2016=100)',
        'frecuencia': 'mensual',
        'unidad': 'índice (base dic-2016=100)',
        'desde': '2016-12-01',
        'hasta': '2026-03-01',
    },
    {
        'id': 'ipc_var_mensual',
        'nombre': 'Inflación Mensual (IPC)',
        'fuente': 'indec',
        'categoria': 'real',
        'archivo': 'data/raw/indec/ipc_nacional_ndice_de_precios_al_consumidor_nivel_general_base_diciembre_.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'ipc_ng_nacional_tasa_variacion_mensual',
        'descripcion': 'Variación mensual del IPC Nacional — inflación mensual',
        'frecuencia': 'mensual',
        'unidad': '% mensual',
        'desde': '2017-01-01',
        'hasta': '2026-03-01',
    },
    {
        'id': 'emae',
        'nombre': 'EMAE (Actividad Económica)',
        'fuente': 'indec',
        'categoria': 'real',
        'archivo': 'data/raw/indec/emae_emae_ndice_base_2004_valores_mensuales.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'emae_original',
        'descripcion': 'Estimador Mensual de Actividad Económica (INDEC), base 2004=100',
        'frecuencia': 'mensual',
        'unidad': 'índice (base 2004=100)',
        'desde': '2004-01-01',
        'hasta': '2026-02-01',
    },
    {
        'id': 'emae_desestac',
        'nombre': 'EMAE Desestacionalizado',
        'fuente': 'indec',
        'categoria': 'real',
        'archivo': 'data/raw/indec/emae_emae_ndice_base_2004_valores_mensuales.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'emae_desestacionalizada',
        'descripcion': 'EMAE desestacionalizado — serie de ciclo-tendencia',
        'frecuencia': 'mensual',
        'unidad': 'índice (base 2004=100)',
        'desde': '2004-01-01',
        'hasta': '2026-02-01',
    },

    # ===================================================================
    # PBI Y CUENTAS NACIONALES (Variables Finales)
    # ===================================================================
    {
        'id': 'pbi_constante_2004',
        'nombre': 'PBI (constante 2004)',
        'fuente': 'indec',
        'categoria': 'real',
        'archivo': 'data/Variables Finales/pbi_constante_2004.csv',
        'col_fecha': 'fecha',
        'col_valor': 'pbi',
        'descripcion': 'Producto Interno Bruto a precios constantes de 2004',
        'frecuencia': 'trimestral',
        'unidad': 'millones ARS',
        'desde': '2004-01-01',
        'hasta': '2026-12-31',
    },
    {
        'id': 'pbi_corriente',
        'nombre': 'PBI (corriente)',
        'fuente': 'indec',
        'categoria': 'real',
        'archivo': 'data/Variables Finales/pbi_corriente.csv',
        'col_fecha': 'fecha',
        'col_valor': 'pbi',
        'descripcion': 'Producto Interno Bruto a precios corrientes',
        'frecuencia': 'trimestral',
        'unidad': 'millones ARS',
        'desde': '2004-01-01',
        'hasta': '2026-12-31',
    },
    {
        'id': 'pbi_usd_mep',
        'nombre': 'PBI — USD MEP',
        'fuente': 'processed',
        'categoria': 'real',
        'archivo': 'data/Variables Finales/pbi_trimestral_usd_mep.csv',
        'col_fecha': 'periodo',
        'col_valor': 'pbi_usd_mm',
        'descripcion': 'Producto Interno Bruto en USD medido al tipo de cambio MEP',
        'frecuencia': 'trimestral',
        'unidad': 'millones USD',
        'desde': '2004-01-01',
        'hasta': '2026-12-31',
    },

    # ===================================================================
    # WORLD BANK
    # ===================================================================
    {
        'id': 'wb_gdp_usd',
        'nombre': 'PBI (USD corrientes)',
        'fuente': 'worldbank',
        'categoria': 'real',
        'archivo': 'data/raw/worldbank/gdp_usd.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Producto Bruto Interno en dólares corrientes (World Bank)',
        'frecuencia': 'anual',
        'unidad': 'USD',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_gdp_pc',
        'nombre': 'PBI per Cápita (USD)',
        'fuente': 'worldbank',
        'categoria': 'real',
        'archivo': 'data/raw/worldbank/gdp_per_capita.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'PBI per cápita en dólares corrientes (World Bank)',
        'frecuencia': 'anual',
        'unidad': 'USD per cápita',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_gdp_growth',
        'nombre': 'Crecimiento PBI (% anual)',
        'fuente': 'worldbank',
        'categoria': 'real',
        'archivo': 'data/raw/worldbank/gdp_growth.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Tasa de crecimiento real del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% anual',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_inflation',
        'nombre': 'Inflación anual (WB)',
        'fuente': 'worldbank',
        'categoria': 'real',
        'archivo': 'data/raw/worldbank/inflation_cpi.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Inflación anual del IPC (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% anual',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_gov_debt',
        'nombre': 'Deuda Pública (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'fiscal',
        'archivo': 'data/raw/worldbank/gov_debt_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Deuda pública bruta como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_exports',
        'nombre': 'Exportaciones (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'externo',
        'archivo': 'data/raw/worldbank/exports_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Exportaciones de bienes y servicios como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_cab',
        'nombre': 'Cuenta Corriente (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'externo',
        'archivo': 'data/raw/worldbank/cab_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Balance de cuenta corriente como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_fdi',
        'nombre': 'IED (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'externo',
        'archivo': 'data/raw/worldbank/fdi_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Inversión Extranjera Directa como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_reserves',
        'nombre': 'Reservas (WB)',
        'fuente': 'worldbank',
        'categoria': 'externo',
        'archivo': 'data/raw/worldbank/reserves.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Reservas internacionales totales incluyendo oro (World Bank)',
        'frecuencia': 'anual',
        'unidad': 'USD',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_unemployment',
        'nombre': 'Desempleo (% PEA)',
        'fuente': 'worldbank',
        'categoria': 'real',
        'archivo': 'data/raw/worldbank/unemployment.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Tasa de desempleo como % de la Población Económicamente Activa (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PEA',
        'desde': '1991-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_wgi_polstab',
        'nombre': 'WGI — Estabilidad Política',
        'fuente': 'worldbank',
        'categoria': 'institucional',
        'archivo': 'data/raw/worldbank/wgi_polstab.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'World Governance Indicator: Estabilidad Política y Ausencia de Violencia',
        'frecuencia': 'anual',
        'unidad': 'puntaje (-2.5 a 2.5)',
        'desde': '1996-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_wgi_goveff',
        'nombre': 'WGI — Efectividad Gubernamental',
        'fuente': 'worldbank',
        'categoria': 'institucional',
        'archivo': 'data/raw/worldbank/wgi_goveff.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'World Governance Indicator: Efectividad del Gobierno',
        'frecuencia': 'anual',
        'unidad': 'puntaje (-2.5 a 2.5)',
        'desde': '1996-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_wgi_rol',
        'nombre': 'WGI — Estado de Derecho',
        'fuente': 'worldbank',
        'categoria': 'institucional',
        'archivo': 'data/raw/worldbank/wgi_rol.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'World Governance Indicator: Estado de Derecho (Rule of Law)',
        'frecuencia': 'anual',
        'unidad': 'puntaje (-2.5 a 2.5)',
        'desde': '1996-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_wgi_corruption',
        'nombre': 'WGI — Control de Corrupción',
        'fuente': 'worldbank',
        'categoria': 'institucional',
        'archivo': 'data/raw/worldbank/wgi_control_corruption.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'World Governance Indicator: Control de la Corrupción',
        'frecuencia': 'anual',
        'unidad': 'puntaje (-2.5 a 2.5)',
        'desde': '1996-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_wgi_regqual',
        'nombre': 'WGI — Calidad Regulatoria',
        'fuente': 'worldbank',
        'categoria': 'institucional',
        'archivo': 'data/raw/worldbank/wgi_regqual.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'World Governance Indicator: Calidad Regulatoria',
        'frecuencia': 'anual',
        'unidad': 'puntaje (-2.5 a 2.5)',
        'desde': '1996-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_wgi_voice',
        'nombre': 'WGI — Voz y Rendición de Cuentas',
        'fuente': 'worldbank',
        'categoria': 'institucional',
        'archivo': 'data/raw/worldbank/wgi_voice_accountability.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'World Governance Indicator: Voz y Rendición de Cuentas',
        'frecuencia': 'anual',
        'unidad': 'puntaje (-2.5 a 2.5)',
        'desde': '1996-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_imports',
        'nombre': 'Importaciones (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'externo',
        'archivo': 'data/raw/worldbank/imports_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Importaciones de bienes y servicios como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_trade',
        'nombre': 'Apertura Comercial (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'externo',
        'archivo': 'data/raw/worldbank/trade_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Suma de exportaciones e importaciones como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_credit_private',
        'nombre': 'Crédito al Sector Privado (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'monetario',
        'archivo': 'data/raw/worldbank/credit_private_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Crédito doméstico al sector privado como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_market_cap',
        'nombre': 'Capitalización de Mercado (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'mercado',
        'archivo': 'data/raw/worldbank/market_cap_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Capitalización bursátil como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_broad_money',
        'nombre': 'Dinero Amplio M2 (% PBI)',
        'fuente': 'worldbank',
        'categoria': 'monetario',
        'archivo': 'data/raw/worldbank/broad_money_gdp.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'M2 como % del PBI (World Bank)',
        'frecuencia': 'anual',
        'unidad': '% PBI',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },
    {
        'id': 'wb_population',
        'nombre': 'Población Total',
        'fuente': 'worldbank',
        'categoria': 'real',
        'archivo': 'data/raw/worldbank/population.csv',
        'col_fecha': 'year',
        'col_valor': 'value',
        'col_pais': 'economy',
        'pais_filtro': 'ARG',
        'descripcion': 'Población total de Argentina (World Bank)',
        'frecuencia': 'anual',
        'unidad': 'personas',
        'desde': '1990-01-01',
        'hasta': '2024-01-01',
    },

    # ===================================================================
    # MECON - Ministerio de Economía
    # ===================================================================
    {
        'id': 'resultado_primario',
        'nombre': 'Resultado Primario SPN (mensual)',
        'fuente': 'mecon',
        'categoria': 'fiscal',
        'archivo': 'data/raw/mecon/imig_spnf_informe_mensual_de_ingresos_y_gastos_sector_p_blico_nacional.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'resultado_primario',
        'descripcion': 'Resultado primario del Sector Público Nacional — Informe Mensual MECON',
        'frecuencia': 'mensual',
        'unidad': 'millones ARS',
        'desde': '2016-01-01',
        'hasta': '2026-03-01',
    },
    {
        'id': 'resultado_financiero',
        'nombre': 'Resultado Financiero SPN (mensual)',
        'fuente': 'mecon',
        'categoria': 'fiscal',
        'archivo': 'data/raw/mecon/imig_spnf_informe_mensual_de_ingresos_y_gastos_sector_p_blico_nacional.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'resultado_financiero',
        'descripcion': 'Resultado financiero del Sector Público Nacional (primario menos intereses)',
        'frecuencia': 'mensual',
        'unidad': 'millones ARS',
        'desde': '2016-01-01',
        'hasta': '2026-03-01',
    },
    {
        'id': 'recursos_tributarios',
        'nombre': 'Recursos Tributarios (mensual)',
        'fuente': 'mecon',
        'categoria': 'fiscal',
        'archivo': 'data/raw/mecon/recursos_tributarios_recursos_tributarios_totales_y_por_tributo_valores_mensuales.csv',
        'col_fecha': 'indice_tiempo',
        'col_valor': 'total_recursos_tributarios',
        'descripcion': 'Recursos tributarios totales recaudados — MECON',
        'frecuencia': 'mensual',
        'unidad': 'millones ARS',
        'desde': '1997-01-01',
        'hasta': '2026-03-01',
    },

    # ===================================================================
    # PROCESSED - Elaboración propia
    # ===================================================================
    {
        'id': 'spread_tasas',
        'nombre': 'Spread de Tasas (elaboración propia)',
        'fuente': 'processed',
        'categoria': 'monetario',
        'archivo': 'data/processed/spread_tasas.csv',
        'col_fecha': 'fecha',
        'col_valor': 'spread_tasas',
        'descripcion': 'Spread entre tasas activas y pasivas del sistema financiero argentino',
        'frecuencia': 'diaria',
        'unidad': 'puntos porcentuales',
        'desde': '2003-01-02',
        'hasta': '2026-04-20',
    },
    {
        'id': 'years_since_default',
        'nombre': 'Años desde último Default',
        'fuente': 'processed',
        'categoria': 'dummy',
        'archivo': 'data/processed/years_since_default.csv',
        'col_fecha': 'fecha',
        'col_valor': 'years_since_default',
        'descripcion': 'Años transcurridos desde el último evento de default soberano argentino',
        'frecuencia': 'diaria',
        'unidad': 'años',
        'desde': '1999-01-01',
        'hasta': '2026-04-20',
    },
    {
        'id': 'dummy_cepo',
        'nombre': 'Dummy Cepo Cambiario',
        'fuente': 'processed',
        'categoria': 'dummy',
        'archivo': 'data/processed/dummy_cepo.csv',
        'col_fecha': 'fecha',
        'col_valor': 'dummy_cepo',
        'descripcion': 'Variable dummy para períodos con control de cambios (cepo cambiario)',
        'frecuencia': 'diaria',
        'unidad': '0 / 1',
        'desde': '1999-01-01',
        'hasta': '2026-04-20',
    },
    {
        'id': 'dummy_electoral',
        'nombre': 'Dummy Electoral',
        'fuente': 'processed',
        'categoria': 'dummy',
        'archivo': 'data/processed/dummy_elec.csv',
        'col_fecha': 'fecha',
        'col_valor': 'dummy_electoral',
        'descripcion': 'Variable dummy para años de elecciones presidenciales',
        'frecuencia': 'diaria',
        'unidad': '0 / 1',
        'desde': '1999-01-01',
        'hasta': '2026-04-20',
    },
    {
        'id': 'dummy_gob',
        'nombre': 'Dummy Gobierno',
        'fuente': 'processed',
        'categoria': 'dummy',
        'archivo': 'data/processed/dummy_gob.csv',
        'col_fecha': 'fecha',
        'col_valor': 'dummy_gob',
        'descripcion': 'Variable dummy para identificar el partido político en el gobierno',
        'frecuencia': 'diaria',
        'unidad': 'categoría',
        'desde': '1999-01-01',
        'hasta': '2026-04-20',
    },
    {
        'id': 'defaults_history',
        'nombre': 'Historial de Defaults',
        'fuente': 'processed',
        'categoria': 'dummy',
        'archivo': 'data/processed/defaults_history.csv',
        'col_fecha': 'fecha',
        'col_valor': 'en_default',
        'descripcion': 'Variable dummy que indica si Argentina estaba en situación de default',
        'frecuencia': 'diaria',
        'unidad': '0 / 1',
        'desde': '1999-01-01',
        'hasta': '2026-04-20',
    },
]

# Índice rápido: id → entrada
_IDX = {e['id']: e for e in GLOSARIO}


def buscar(texto: str = '', fuente: str = '', categoria: str = '') -> pd.DataFrame:
    """Filtra el glosario y devuelve un DataFrame."""
    resultado = GLOSARIO
    if fuente:
        resultado = [e for e in resultado if e['fuente'] == fuente]
    if categoria:
        resultado = [e for e in resultado if e['categoria'] == categoria]
    if texto:
        txt = texto.lower()
        resultado = [e for e in resultado
                     if txt in e['nombre'].lower() or txt in e['descripcion'].lower() or txt in e['id']]
    cols = ['id', 'nombre', 'fuente', 'categoria', 'frecuencia', 'unidad', 'desde', 'hasta', 'descripcion']
    df = pd.DataFrame([{k: e.get(k, 'N/A') for k in cols + ['disponible']} for e in resultado])
    # disponible por defecto es True si no está definido
    df['disponible'] = df['disponible'].apply(lambda x: x if isinstance(x, bool) else True)
    df['disponible'] = df['disponible'].map({True: '✅', False: '⚠️ Sin datos'})
    return df[cols + ['disponible']]


def get(serie_id: str) -> Optional[dict]:
    """Devuelve la entrada del glosario para un ID dado."""
    return _IDX.get(serie_id)


def cargar_serie(
    serie_id: str,
    fecha_inicio: Optional[str] = None,
    fecha_fin: Optional[str] = None,
    frecuencia: Optional[str] = None,
) -> Optional[pd.Series]:
    """
    Carga una serie de tiempo desde el archivo CSV correspondiente en el glosario.

    Args:
        serie_id:    ID del glosario (ej: 'embi_arg', 'vix', 'tc_blue').
        fecha_inicio: Fecha de inicio 'YYYY-MM-DD'. Si None, usa toda la historia.
        fecha_fin:   Fecha fin 'YYYY-MM-DD'. Si None, hasta hoy.
        frecuencia:  Resampleo: 'D', 'W', 'M', 'Q', 'A'. Si None, frecuencia original.

    Returns:
        pd.Series con DatetimeIndex y nombre = serie_id, o None si hay error.
    """
    entry = get(serie_id)
    if entry is None:
        print(f"[ERROR] Serie '{serie_id}' no encontrada en el glosario.")
        print(f"    IDs disponibles: {list(_IDX.keys())}")
        return None

    # Verificar si la serie está marcada como no disponible
    if not entry.get('disponible', True):
        print(f"⚠️  Serie '{serie_id}' ({entry['nombre']}) no está disponible: {entry['descripcion']}")
        return None

    path = os.path.join(_BASE, entry['archivo'].replace('/', os.sep))
    if not os.path.exists(path):
        print(f"[ERROR] Archivo no encontrado: {path}")
        return None

    try:
        df = pd.read_csv(path, low_memory=False)
    except Exception as e:
        print(f"[ERROR] Error leyendo {path}: {e}")
        return None

    # --- parsear columna fecha ---
    col_fecha = entry['col_fecha']
    col_valor = entry['col_valor']

    if col_fecha not in df.columns:
        print(f"❌  Columna '{col_fecha}' no encontrada en {path}.")
        print(f"    Columnas disponibles: {list(df.columns)}")
        return None

    # World Bank: filtrar por país antes de procesar fechas
    if 'col_pais' in entry:
        df = df[df[entry['col_pais']] == entry['pais_filtro']].copy()
        # La columna 'year' contiene enteros, convertir a fecha
        df['_fecha_parsed'] = pd.to_datetime(df[col_fecha].astype(str) + '-01-01', errors='coerce')
    else:
        df['_fecha_parsed'] = pd.to_datetime(df[col_fecha], errors='coerce')

    df = df.dropna(subset=['_fecha_parsed'])
    df = df.set_index('_fecha_parsed')
    df.index.name = 'fecha'
    df = df.sort_index()

    if col_valor not in df.columns:
        print(f"❌  Columna '{col_valor}' no encontrada en {path}.")
        print(f"    Columnas disponibles: {list(df.columns)}")
        return None

    serie = pd.to_numeric(df[col_valor], errors='coerce').dropna()
    serie.name = serie_id

    # --- filtrar fechas ---
    if fecha_inicio:
        serie = serie[serie.index >= pd.Timestamp(fecha_inicio)]
    if fecha_fin:
        serie = serie[serie.index <= pd.Timestamp(fecha_fin)]

    if serie.empty:
        print(f"⚠️  Serie '{serie_id}' vacía con el rango de fechas especificado.")
        return None

    # --- resampleo ---
    if frecuencia:
        freq_map = {'D': 'D', 'W': 'W', 'M': 'M', 'Q': 'Q', 'A': 'A'}
        resample_freq = freq_map.get(frecuencia.upper(), frecuencia)
        serie = serie.resample(resample_freq).last().ffill()

    return serie


def info(serie_id: str) -> None:
    """Imprime información detallada sobre una serie."""
    entry = get(serie_id)
    if entry is None:
        print(f"Serie '{serie_id}' no encontrada.")
        return
    print(f"{'='*55}")
    print(f"  {entry['nombre']}")
    print(f"{'='*55}")
    for k, v in entry.items():
        if k not in ('archivo', 'col_fecha', 'col_valor', 'col_pais', 'pais_filtro'):
            print(f"  {k:<15} {v}")
    print(f"  {'archivo':<15} {entry['archivo']}")
    print(f"{'='*55}")
